# Generated by Django 4.1 on 2023-03-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dkmapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Family',
            new_name='DKM',
        ),
    ]
