# Generated by Django 4.1 on 2023-03-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkmapp', '0003_dkm_prodi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dkm',
            name='relation',
            field=models.CharField(blank=True, choices=[('tingkat 1', 'tingkat 1'), ('tingkat 2', 'tingkat 2')], max_length=200, null=True),
        ),
    ]
