# Generated by Django 4.1 on 2023-03-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkmapp', '0005_alter_dkm_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dkm',
            name='relation',
        ),
        migrations.AddField(
            model_name='dkm',
            name='jabatan',
            field=models.CharField(blank=True, choices=[('ketua', 'ketua'), ('sekretaris', 'sekretaris'), ('Koordinator Public Relation', 'Koordinator Public Relation'), ('Koordinator Event Organizer', 'Koordinator Event Organizer'), ('Koordinator Media', 'Koordinator Media'), ('Koordinator Fasilitator FKIP', 'Koordinator Fasilitator FKIP'), ('Koordinator Fasilitator FISIP', 'Koordinator Fasilitator FISIP'), ('Koordinator Fasilitator FEB', 'Koordinator Fasilitator FEB'), ('Koordinator Fasilitator FAHUM', 'Koordinator Fasilitator FAHUM'), ('Koordinator Fasilitator FATEK', 'Koordinator Fasilitator FATEK'), ('Koordinator Fasilitator FMIPA', 'Koordinator Fasilitator FMIPA'), ('Koordinator Fasilitator FAPERTA', 'Koordinator Fasilitator FAPERTA'), ('Koordinator Fasilitator FAPETKAN', 'Koordinator Fasilitator FAPETKAN'), ('Koordinator Fasilitator FKM', 'Koordinator Fasilitator FKM'), ('Anggota Fasilitator FKIP', 'Anggota Fasilitator FKIP'), ('Anggota Fasilitator FISIP', 'Anggota Fasilitator FISIP'), ('Anggota Fasilitator FEB', 'Anggota Fasilitator FEB'), ('Anggota Fasilitator FAHUM', 'Anggota Fasilitator FAHUM'), ('Anggota Fasilitator FATEK', 'Anggota Fasilitator FATEK'), ('Anggota Fasilitator FMIPA', 'Anggota Fasilitator FMIPA'), ('Anggota Fasilitator FAPERTA', 'Anggota Fasilitator FAPERTA'), ('Anggota Fasilitator FAPETKAN', 'Anggota Fasilitator FAPETKAN'), ('Anggota Fasilitator FKM', 'Anggota Fasilitator FKM')], max_length=100, null=True),
        ),
    ]
