# Generated by Django 4.1 on 2023-03-29 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dkmapp', '0008_alter_dkm_jabatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postingan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, auto_now_add=True)),
                ('nama_postingan', models.CharField(max_length=50, null=True)),
                ('post', models.FileField(upload_to='post')),
            ],
        ),
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20, null=True)),
                ('testimoni', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dkm',
            name='jabatan',
            field=models.CharField(blank=True, choices=[('ketua', 'ketua'), ('sekretaris', 'sekretaris'), ('Koordinator Public Relation', 'Koordinator Public Relation'), ('Koordinator Event Organizer', 'Koordinator Event Organizer'), ('Koordinator Creative marketing & Promotion', 'Koordinator Creative marketing & Promotion'), ('Koordinator Fasilitator FKIP', 'Koordinator Fasilitator FKIP'), ('Koordinator Fasilitator FISIP', 'Koordinator Fasilitator FISIP'), ('Koordinator Fasilitator FEB', 'Koordinator Fasilitator FEB'), ('Koordinator Fasilitator FAHUM', 'Koordinator Fasilitator FAHUM'), ('Koordinator Fasilitator FATEK', 'Koordinator Fasilitator FATEK'), ('Koordinator Fasilitator FMIPA', 'Koordinator Fasilitator FMIPA'), ('Koordinator Fasilitator FAPERTA', 'Koordinator Fasilitator FAPERTA'), ('Koordinator Fasilitator FAPETKAN', 'Koordinator Fasilitator FAPETKAN'), ('Koordinator Fasilitator FKM', 'Koordinator Fasilitator FKM'), ('Koordinator Fasilitator FAHUT', 'Koordinator Fasilitator FAHUT'), ('Anggota Public Relation', 'Anggota Public Relation'), ('Anggota Event Organizer', 'Anggota Event Organizer'), ('Anggota Creative marketing & Promotion', 'Anggota Creative marketing & Promotion'), ('Anggota Fasilitator FKIP', 'Anggota Fasilitator FKIP'), ('Anggota Fasilitator FISIP', 'Anggota Fasilitator FISIP'), ('Anggota Fasilitator FEB', 'Anggota Fasilitator FEB'), ('Anggota Fasilitator FAHUM', 'Anggota Fasilitator FAHUM'), ('Anggota Fasilitator FATEK', 'Anggota Fasilitator FATEK'), ('Anggota Fasilitator FMIPA', 'Anggota Fasilitator FMIPA'), ('Anggota Fasilitator FAPERTA', 'Anggota Fasilitator FAPERTA'), ('Anggota Fasilitator FAPETKAN', 'Anggota Fasilitator FAPETKAN'), ('Anggota Fasilitator FKM', 'Anggota Fasilitator FKM'), ('Anggota Fasilitator FAHUT', 'Anggota Fasilitator FAHUT')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Ulasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pemberi_ulasan', models.CharField(blank=True, max_length=20, null=True)),
                ('ulasan', models.IntegerField()),
                ('diulas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dkmapp.dkm')),
            ],
        ),
        migrations.CreateModel(
            name='Pertanyaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=9, null=True)),
                ('nama', models.CharField(max_length=30, null=True)),
                ('pertanyaan', models.CharField(max_length=100, null=True)),
                ('jawaban', models.CharField(max_length=300, null=True)),
                ('pemberi_jawaban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dkmapp.dkm')),
            ],
        ),
        migrations.CreateModel(
            name='Nilai_DKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField(blank=True, default=5.0, null=True)),
                ('dkm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dkmapp.dkm')),
            ],
        ),
    ]
