# Generated by Django 4.1 on 2023-03-30 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dkmapp', '0011_rename_nama_postingan_postingan_judul_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimoni',
            name='nama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dkmapp.dkm'),
        ),
    ]
