# Generated by Django 4.1 on 2023-03-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkmapp', '0012_alter_testimoni_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimoni',
            name='nama',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
