# Generated by Django 4.1 on 2023-03-30 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dkmapp', '0014_alter_testimoni_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimoni',
            name='nama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dkmapp.dkm'),
        ),
    ]
