# Generated by Django 4.1 on 2023-03-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkmapp', '0015_alter_testimoni_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingan',
            name='caption',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
