# Generated by Django 4.1 on 2023-03-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkmapp', '0017_alter_pertanyaan_jawaban_alter_pertanyaan_nama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertanyaan',
            name='jawaban',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pertanyaan',
            name='pertanyaan',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
