# Generated by Django 4.1 on 2023-03-31 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dkmapp', '0018_alter_pertanyaan_jawaban_alter_pertanyaan_pertanyaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertanyaan',
            name='pemberi_jawaban',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dkmapp.dkm'),
        ),
    ]
