# Generated by Django 4.1 on 2023-03-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkmapp', '0019_alter_pertanyaan_pemberi_jawaban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dkm',
            name='jabatan',
            field=models.CharField(blank=True, choices=[('ketua', 'ketua'), ('sekretaris', 'sekretaris'), ('bendahara', 'bendahara'), ('Koordinator Public Relation', 'Koordinator Public Relation'), ('Koordinator Event Organizer', 'Koordinator Event Organizer'), ('Koordinator Creative marketing & Promotion', 'Koordinator Creative marketing & Promotion'), ('PIC Fasilitator FKIP', 'PIC Fasilitator FKIP'), ('PIC Fasilitator FISIP', 'PIC Fasilitator FISIP'), ('PIC Fasilitator FEB', 'PIC Fasilitator FEB'), ('PIC Fasilitator FAHUM', 'PIC Fasilitator FAHUM'), ('PIC Fasilitator FATEK', 'PIC Fasilitator FATEK'), ('PIC Fasilitator FMIPA', 'PIC Fasilitator FMIPA'), ('PIC Fasilitator FAPERTA', 'PIC Fasilitator FAPERTA'), ('PIC Fasilitator FAPETKAN', 'PIC Fasilitator FAPETKAN'), ('PIC Fasilitator FKM', 'PIC Fasilitator FKM'), ('PIC Fasilitator FAHUT', 'PIC Fasilitator FAHUT'), ('Anggota Public Relation', 'Anggota Public Relation'), ('Anggota Event Organizer', 'Anggota Event Organizer'), ('Anggota Creative marketing & Promotion', 'Anggota Creative marketing & Promotion'), ('Fasilitator FKIP', 'Fasilitator FKIP'), ('Fasilitator FISIP', 'Fasilitator FISIP'), ('Fasilitator FEB', 'Fasilitator FEB'), ('Fasilitator FAHUM', 'Fasilitator FAHUM'), ('Fasilitator FATEK', 'Fasilitator FATEK'), ('Fasilitator FMIPA', 'Fasilitator FMIPA'), ('Fasilitator FAPERTA', 'Fasilitator FAPERTA'), ('Fasilitator FAPETKAN', 'Fasilitator FAPETKAN'), ('Fasilitator FKM', 'Fasilitator FKM'), ('Fasilitator FAHUT', 'Fasilitator FAHUT')], max_length=100, null=True),
        ),
    ]
