# Generated by Django 4.1 on 2023-03-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkmapp', '0020_alter_dkm_jabatan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dkm',
            name='fid',
        ),
        migrations.RemoveField(
            model_name='dkm',
            name='mid',
        ),
        migrations.RemoveField(
            model_name='dkm',
            name='pids',
        ),
        migrations.AddField(
            model_name='dkm',
            name='instagram',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dkm',
            name='linkedin',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
