# Generated by Django 4.1 on 2023-03-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkmapp', '0021_remove_dkm_fid_remove_dkm_mid_remove_dkm_pids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulasan',
            name='bintang',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ulasan',
            name='ulasan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
