# Generated by Django 4.1 on 2023-03-31 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dkmapp', '0022_ulasan_bintang_alter_ulasan_ulasan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ulasan',
            name='pemberi_ulasan',
        ),
    ]
