# Generated by Django 4.1 on 2023-04-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkmapp', '0024_dkm_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='dkm',
            name='pengalaman',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
